### ISSUE TITLE
Local storage value with quotes?

### ISSUE THREAD

**Issue by vbgm** [VeliovGroup/Client-Storage#1]
The ClientStorage.set() seem to set the value with quotes included. Has it been done on purpose?
For example:

```
const test = 'someString';
ClientStorage.set('test1', test);
localStorage.setItem('test2', test);
```

The test1 is saved in local storage as "someString" (with quotes) whereas test2 just as someString (without quotes). The 'local storage only' mode also saves with the quotes.

**Comment by dr-dimitru** [comment]
@vblagomir it's done for [char escaping](https://github.com/VeliovGroup/Client-Storage/blob/master/client-storage.js#L317) purpose. It returns value without quotes right?

**Comment by vbgm** [comment]
I did not check what it returns, just what it sets into local storage, and it looks inconsistent compared to meteor tokens.

**Comment by dr-dimitru** [comment]
@vblagomir yes, in short - it's done on purpose.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if issue still persists on your end.
