### ISSUE TITLE
please add support of timeout expiration option

### ISSUE THREAD

**Issue by bobagold** [VeliovGroup/Client-Storage#2]
it can be useful to set some key-value pair for limited time, for example, 1 hour or 1 day

**Comment by dr-dimitru** [comment]
Hello @bobagold ,

Thank you for this request, I know it took years to implement it 🤦‍♂️ , final solution released as [`v3.0.0`](https://github.com/VeliovGroup/Client-Storage/releases/tag/3.0.0).
Let me know wdyt. Feel free to reopen it in case if the issue is still persists on your end.
