### ISSUE TITLE
Reactivity

### ISSUE THREAD

**Issue by EulerTourist** [VeliovGroup/Client-Storage#3]
What is the most elegant what to make this reactive within Meteor?

**Comment by dr-dimitru** [comment]
Hello @EulerTourist ,

I usually wrap it into *ReactiveVar* (*not a great idea*), or you can extend it with *ReactiveDict*.

Here is snippet for *ReactiveVar*:

```js
const ClientStorage = require('ClientStorage').ClientStorage;
// or 
// import { ClientStorage } from 'ClientStorage';

const defaultValue = 'MyDefaultValue';
const permanentReactiveVar = new ReactiveVar(ClientStorage.has('key') ? ClientStorage.get('key') : defaultValue);
permanentReactiveVar.set = function(newValue) {
  let oldValue = this.curValue;
  if ((this.equalsFunc || ReactiveVar._isEqual)(oldValue, newValue)) {
    return;
  }
  this.curValue = newValue;
  ClientStorage.set('key', newValue);
  this.dep.changed();
};
```

Let me know if this is helpful.

**Comment by dr-dimitru** [comment]
@EulerTourist might be a good idea to implement this as addon?

**Comment by dr-dimitru** [comment]
Hello @EulerTourist 👋,

Solved as [code sample in docs](https://github.com/VeliovGroup/Client-Storage#meteor-add-reactivity). Feel free to reopen it in case if the issue is still persists on your end.

Sorry for delay, and thank you for the great question 😉
