### ISSUE TITLE
Can't use it on Meteor v2.3.2

### ISSUE THREAD

**Issue by carlosalvidrez** [VeliovGroup/Client-Storage#6]
### I'm having an issue:
Upgrading from Meteor 2.2.0 to 2.3.2.
I am using packages ostrio:cookies and ostrio:i18n... one of those seems to have a dependency on otrio:cstorage

### I have a suggestion:
Re-declare the dependencies and update so we can upgrade to Meteor 2.3.2.

Thank you so much for sharing your packages, they are great.

Warning message from the console, which I get after upgrading to v2.3.2:
`updated to Meteor 2.3.2.    
Your top-level dependencies are at their latest compatible versions.
                                              
Newer versions of the following indirect dependencies are available:
 * ostrio:cstorage 2.2.2 (3.0.1 is available) 
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.

`

**Comment by dr-dimitru** [comment]
Hello @carlosalvidrez 

I'm sorry that I've missed your post back year ago. Please try to update to `@4.0.0`, this issue should be solved

Feel free to close it in case if the issue is solved on your end.

**Comment by carlosalvidrez** [comment]
Thanks, I appreciate it. When removing the hard-coded version 3.0.1, I got this error message... looks like there is a dependency on your cstorage old version 2.2.1, from ostrio:i18n.  

Pasting the error here, hoping this might be a simple fix. 
Thank you for sharing your libraries.


`This project is already at Meteor 2.7.2, the latest release.
=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: Potentially incompatible change required to top-level dependency: ostrio:cstorage 2.2.2, was 3.0.1.
Constraints on package "ostrio:cstorage":
* ostrio:cstorage@2.2.1 <- ostrio:i18n 3.1.0

To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.

                                              
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
`

**Comment by carlosalvidrez** [comment]
By the way, I did get an error in my app after forcing to version 4.0.0... placing it here in case it helps, and hoping you might be able to modernize the ostrio:i18n package too : )

`Uncaught TypeError: ClientStorage.get is not a function
    at new I18N (i18n.js:125:41)
    at setI18n (i18n.js:42:16)
    at startup.js:2:8
    at module (startup.js:5:1)
    at fileEvaluate (modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:388:7)
    at Module.require (modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:270:27)
    at require (modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:310:21)
    at useraccounts.js:228:1
client.startup.js:157 Uncaught ReferenceError: i18n is not defined
    at client.startup.js:157:35
    at maybeReady (meteor.js?hash=b9ec8cf25b6fc794ae6b825f30e06c3c35c50e7c:943:28)
    at HTMLDocument.loadingCompleted (meteor.js?hash=b9ec8cf25b6fc794ae6b825f30e06c3c35c50e7c:955:5)`

**Comment by dr-dimitru** [comment]
@carlosalvidrez thank you for the valuable input, update of `i18n` is on its way

**Comment by dr-dimitru** [comment]
@carlosalvidrez this issue should be solved in [`meteor/ostrio:i18n@3.2.0`](https://github.com/veliovgroup/Meteor-Internationalization/releases/tag/3.2.0), please upgrade

Feel free to close it in case if the issue is solved on your end.

**Comment by carlosalvidrez** [comment]
Worked like a charm, thank you!
